<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>io.github.christophknabe</groupId>
        <artifactId>multex</artifactId>
        <version>${revision}</version>
    </parent>

    <artifactId>multex-demo</artifactId>

    <properties>
        <maven.compiler.source>8</maven.compiler.source>
        <maven.compiler.target>8</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <dependencies>
        <dependency>
            <groupId>io.github.christophknabe</groupId>
            <artifactId>multex-core</artifactId>
        </dependency>
        <dependency>
            <groupId>io.github.christophknabe</groupId>
            <artifactId>multex-tool</artifactId>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <configuration>
                    <source>1.8</source>
                    <target>1.8</target>
                    <annotationProcessors>
                        <annotationProcessor>
                            io.github.christophknabe.multex.tool.MultexAnnotationProcessor
                        </annotationProcessor>
                    </annotationProcessors>

                    <annotationProcessorPaths>
                        <!-- Add your processor dependency here -->
                        <path>
                            <groupId>io.github.christophknabe</groupId>
                            <artifactId>multex-tool</artifactId>
                            <version>${project.version}</version>
                        </path>
                    </annotationProcessorPaths>
                    <compilerArgs>
                        <!-- Optional: Pass arguments to the processor -->
                        <arg>-Adebug</arg>
                    </compilerArgs>
                </configuration>
            </plugin>
        </plugins>
    </build>

</project>